<a href="https://colab.research.google.com/github/khaylee1/Laboratory-6/blob/main/lab6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

##<b>Task 1</b>

Create a function named mat_desc() that througouhly describes a matrix, it should:

1.) Displays the shape, size, and rank of the matrix.<br>
2.)Displays whether the matrix is square or non-square.<br>
3.)Displays whether the matrix is an empty matrix.<br>
4.Displays if the matrix is an identity, ones, or zeros matrix
##<b>Function:

In [3]:
def mat_desc(matrix):
    if matrix.size >0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nSize: \t{matrix.size}\nRank: \t{np.linalg.matrix_rank(matrix)}\nMatrix Is Square: {is_square}\nMatrix Is Not Null\nIdentity matrix:\t\n{np.eye(3)}')
       
    else:
        print('Matrix is Null')

##<b>Declaration of Vector:

$$X=\begin{bmatrix}8,7,6\\6,1,2\\0,4,1\end{bmatrix}$$

In [7]:
X=np.array([
            [8,7,6],
            [6,1,2],
            [0,4,1]
            ])

##<B>Test Area/ Output:

In [8]:
mat_desc(X)


Matrix:
[[8 7 6]
 [6 1 2]
 [0 4 1]]

Shape:	(3, 3)
Size: 	9
Rank: 	3
Matrix Is Square: True
Matrix Is Not Null
Identity matrix:	
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## <b> Task 2 </b>

Create a function named mat_operations() that takes in two matrices or scalars a input parameters it should:<br>
1.)Display the description of each matrix, if the parameter is a scalar it<br> 
2.)tells that it is a scalar rather than describing it as a matrix.<br>
3.)Determines if the matrices are viable for operation and returns your own error message if they are not viable.<br>
4.)Returns the sum of the matrices.<br>
5.)Returns the differen of the matrices.<br>
6.)Returns the element-wise multiplication of the matrices.<br>
7.)Returns the element-wise division of the matrices.
##<b>Function:


In [ ]:
def mat_operations(matrix,matrix1):
  if matrix.size and matrix1.size >0:
    print(f'Matrix 1:\n{matrix}\n\nMatrix 2:\n{matrix1}\n\nShape of matrix 1:\t{matrix.shape}\nShape of matrix 2:\t{matrix1.shape}\nSize of matrix 1:\t{matrix.size}\nSize of matrix 2:\t{matrix1.size}\nRank of matrix 1:\t{np.linalg.matrix_rank(matrix)}\nRank of matrix 2:\t{np.linalg.matrix_rank(matrix1)}\n\n   Matrix Algebra\n\nSum of the matrix 1 and 2:\t\n{matrix+matrix1}\n\nDifference of the matrix 1 and 2:\t\n{matrix-matrix1}\n\nElement-wise Multiplication of the matrices:\t\n{matrix*matrix1}\n\nElement-wise Division of the matrices:\t\n{matrix/matrix1} ')
  elif matrix.size >0 and matrix1.size ==0:
    print(f'Matrix 1:\n{matrix}\n\nShape:\t{matrix.shape}\nSize: \t{matrix.size}\nRank: \t{np.linalg.matrix_rank(matrix)}\n\n Matrix 2 is null\n\n can not perform operations')
  elif matrix.size ==0 and matrix1.size >0 :
    print(f'Matrix 1 is null \n\ncan not perform operation \n\nMatrix 2:\n{matrix1}\n\nShape:\t{matrix1.shape}\nSize: \t{matrix1.size}\nRank: \t{np.linalg.matrix_rank(matrix1)}\n')
  else:
    print('Both Matrix is Null')

##<b> Decalration of Vector:

$$ K=\begin{bmatrix}1,3,1\\2,3,2\\1,1,2\\\end{bmatrix}\;\;\;J=\begin{bmatrix}2,2,1\\3,1,1\\2,1,2\\\end{bmatrix}$$



In [ ]:
K=np.array([
            [1,3,1],
            [2,3,2],
            [3,3,2]
])
J=np.array([
            [2,2,1],
            [3,1,1],
            [2,3,2]
])

##<b>Test Area/Otput:

In [ ]:
mat_operations(K,J)

Matrix 1:
[[1 3 1]
 [2 3 2]
 [3 3 2]]

Matrix 2:
[[2 2 1]
 [3 1 1]
 [2 3 2]]

Shape of matrix 1:	(3, 3)
Shape of matrix 2:	(3, 3)
Size of matrix 1:	9
Size of matrix 2:	9
Rank of matrix 1:	3
Rank of matrix 2:	3

   Matrix Algebra

Sum of the matrix 1 and 2:	
[[3 5 2]
 [5 4 3]
 [5 6 4]]

Difference of the matrix 1 and 2:	
[[-1  1  0]
 [-1  2  1]
 [ 1  0  0]]

Element-wise Multiplication of the matrices:	
[[2 6 1]
 [6 3 2]
 [6 9 4]]

Element-wise Division of the matrices:	
[[0.5        1.5        1.        ]
 [0.66666667 3.         2.        ]
 [1.5        1.         1.        ]] 
